### ISSUE TITLE
nafsdm-slave starts before system has internet connection

### ISSUE THREAD

**Issue by vilhelmprytz** [MrKaKisen/dns-manager#22]
Operating system: All operating systems

nafsdm version: test on 1.3-stable and dev 1.3.1, but may be all versions

Issue: nafsdm will start before the system has internet connection causing slaves to crash

How to reproduce it: just 

Suggested solution (if any): add "Wants" and "After" the network-online.target in systemd file.

```
May 14 21:41:30 debian-slave start.py[323]: 2018-05-14 21:41:30,585 INFO *******************************************************
May 14 21:41:30 debian-slave start.py[323]: 2018-05-14 21:41:30,585 INFO nafsdm-slave daemon - running version 183d062-dev
May 14 21:41:30 debian-slave start.py[323]: 2018-05-14 21:41:30,585 INFO *******************************************************
May 14 21:41:30 debian-slave start.py[323]: 2018-05-14 21:41:30,585 INFO Running pre-start checks..
May 14 21:41:30 debian-slave start.py[323]: 2018-05-14 21:41:30,585 INFO No other instances of nafsdm found.
May 14 21:41:30 debian-slave start.py[323]: 2018-05-14 21:41:30,586 INFO nafsdm running on PID 323
May 14 21:41:30 debian-slave start.py[323]: 2018-05-14 21:41:30,586 DEBUG Temp folder already exists.
May 14 21:41:30 debian-slave start.py[323]: 2018-05-14 21:41:30,586 INFO Checking for new versions..
May 14 21:41:30 debian-slave start.py[323]: 2018-05-14 21:41:30,588 DEBUG Starting new HTTPS connection (1): raw.githubusercontent.com
May 14 21:41:30 debian-slave start.py[323]: Traceback (most recent call last):
May 14 21:41:30 debian-slave start.py[323]:   File "/home/slave-nafsdm/start.py", line 5, in <module>
May 14 21:41:30 debian-slave start.py[323]:     main()
May 14 21:41:30 debian-slave start.py[323]:   File "/home/slave-nafsdm/pythondaemon/__main__.py", line 130, in main
May 14 21:41:30 debian-slave start.py[323]:     checkUpdate(config, None)
May 14 21:41:30 debian-slave start.py[323]:   File "/home/slave-nafsdm/pythondaemon/versionCheck.py", line 63, in checkUpdate
May 14 21:41:30 debian-slave start.py[323]:     r = requests.get("https://raw.githubusercontent.com/MrKaKisen/nafsdm/" + github_branch + "/version.txt")
May 14 21:41:30 debian-slave start.py[323]:   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 72, in get
May 14 21:41:30 debian-slave start.py[323]:     return request('get', url, params=params, **kwargs)
May 14 21:41:30 debian-slave start.py[323]:   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
May 14 21:41:30 debian-slave start.py[323]:     return session.request(method=method, url=url, **kwargs)
May 14 21:41:30 debian-slave start.py[323]:   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
May 14 21:41:30 debian-slave start.py[323]:     resp = self.send(prep, **send_kwargs)
May 14 21:41:30 debian-slave start.py[323]:   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
May 14 21:41:30 debian-slave start.py[323]:     r = adapter.send(request, **kwargs)
May 14 21:41:30 debian-slave start.py[323]:   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
May 14 21:41:30 debian-slave start.py[323]:     raise ConnectionError(e, request=request)
May 14 21:41:30 debian-slave start.py[323]: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /MrKaKisen/nafsdm/development/version.txt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fba8be61550>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
May 14 21:41:30 debian-slave systemd[1]: nafsdm-slave.service: Main process exited, code=exited, status=1/FAILURE
May 14 21:41:30 debian-slave systemd[1]: nafsdm-slave.service: Unit entered failed state.
May 14 21:41:30 debian-slave systemd[1]: nafsdm-slave.service: Failed with result 'exit-code'.
May 14 21:41:32 debian-slave kernel: [    4.222469] e1000: enp0s3 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
```

**Comment by vilhelmprytz** [comment]
This issue is fixed in 1.3.1-stable release.

Please upgrade as soon as possible!
